services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./certs/dev.local.crt.pem:/etc/ssl/certs/dev.local.crt.pem:ro
      - ./certs/dev.local.key.pem:/etc/ssl/private/dev.local.key.pem:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/conf.d:/etc/nginx/conf.d:ro
      - ./config/index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dev.local

networks:
  dev.local:
    external: true